### PR TITLE
Preliminary request

### PR DESCRIPTION
**Pull request by rmusser01**
First, thank you!

Second, I've gone ahead and added a bit of functionality, moved most of your samples to 'Samples' and other summarization scripts to 'tldw-scripts'

The ./Bin folder needs to be cleared of ffmpeg and the functionality put in proper, otherwise it's just a fat binary taking up space on linux/mac users machines. This is the next thing I intend to do, replace the fat binary with a script to give the user to dl the zip and extract the exe to the ./Bin folder, or tell them to install if on linux.

I just added a function and some config options for llama.cpp, but haven't tested it. Plan to test it + start writing tests for the functions at the same time.

Ideally, I'd like to push things forward to the point where the project can be 'packaged' as a self-contained python project, and then used without concern about packages outside of it breaking. This is my 3rd goal, so that it can be brought up/down more easily without concern for package hell.

In tie with the packaging is doing more research on summarization techniques/approaches, as its all new to me so I'm completely naive to approaches.
I did see https://cookbook.openai.com/examples/summarizing_long_documents , which I intended to look at more closely and attempt to implement for this project, after confirming it would be effective.

### CODE REVIEW

**Comment by the-crypt-keeper** [comment]
@rmusser01 Thanks again for the PR!  I had a look over it tonight, here's a few thoughts:

1) One obstacle towards publishing this as a stand-alone tool is that the pyannote models are behind a bit of an approval wall so its probably worth adding a section in the README on where exactly to go on HF to get the approval and to make sure you have the HF token setup or it won't be able to diarize.  There may be other diarization pipeline options that don't have this caveat, pyannote is just what I found first that wasn't full of magic and let me sync up the speech embeddings to the whisper outputs.

2) Love all the quality-of-life and usability improvements, the ASCII art is fabulous 😄 

3) You're spending a lot of effort supporting different LLM providers, I'd recommend offloading all that boilerplate to a library suited for this purpose such as [lite-llm](https://github.com/BerriAI/litellm) then you'll never have to add another one.

4) It looks like the processing pipe currently returns just a single summary of the entire video?  My primary usecase here is 3+ hour long, very long videos.  My original pipe split the dialogue into ~5-minute chunks and then summarized each of those while rolling forward context information, I found this has two benefits over all-at-once: much higher detail level in each summary (since much less input to LLM) and if a 5 minute summary was interesting, you could go back and read the full text of just that portion.  I was thinking of adding a front-end that embeded youtube players with the start time set to each segment so you could also just watch that part of the video easily.  Are you open to re-integrating this part of the pipe?

**Comment by rmusser01** [comment]
Thank you!
@the-crypt-keeper Absolutely, thank you for the comment.
1. Yea, I realized this looking more into packaging, and kinda figured "I'll deal with it when I get around to it". This could prevent packaging being a thing...
2. Thank you!
3. Holy shit, thank you.
4. Yea,I finally took a look in detail at your processing pipeline and noticed that it was aiming for the 'rolling-summarization' based off long-context videos (like you say in your comment).
  * Very interesting, yea that matched with what little I've read of the research into summarization (literally didn't know it was a field of research as of a couple weeks ago... I knew of text classification, but didn't think past that)
  * Which is all to say, absolutely!
 
  I am currently trying to figure out getting a gradio UI that works with HF as a default API and then letting the user select any other ones they might want for demo/non-personal LLM purposes.
  * i.e. Have a gradio UI that non-technical individuals can use, and also have the option within it for 'faster' inference if wanted.

My goal after getting the gradio UI sorted is implemementing the rolling summarization ala the OpenAI cookbook link above. With that, the goal will be implementing the rolling summarization technique for longer videos.

I had planned on figuring out how to identify time-stamps for various bits, and then giving a user a direct link to that timestamp to review the content. I figured that would be the easiest method of showing the relevant bits, with the least amount of hassle. (If you think doing embeds would be easier 👍 )

My overall goal / motivation for all this is to create a simple-to-use tool, that allows anyone to quickly and efficiently consume video content through text. It started for me as a means of quickly consuming conference videos (this project seemed the closest to my goal), and has expanded from there. So adding additional features or use-cases to fit that (long, long videos like you're mentioning) is definitely a part of that.

I am hoping to get that implemented this weekend as I'm only working on this in my free time. But getting this all working nicely is my main project right now.

**Comment by the-crypt-keeper** [comment]
@rmusser01 I've invited you as contributor to this repo.

**Comment by rmusser01** [comment]
@the-crypt-keeper 
Thank you! 

I will plan to make the merge as soon as I have the Gradio UI working properly. Should be a day or so. 🤞  (I'd like it to be at a point where people can clone, install, and then immediatley interact with it via the WebUI, as since I first started, my opinions on the web UI have done a complete 180.)

Additionally/however, something that I thought of after, was the following:

I wanted to clarify the licensing of the repo.
You currently don't have a license attached/declared in your original repo, and I have licensed all my modifications as Apache 2.0.

I would like to keep this and apply this license to the project as a whole, to ensure that it remains free, and available to any/all interested parties.

Would you be open to this?

**Comment by rmusser01** [comment]
Ok, going to work on adding chunking/rolling summarization support for OpenAI tomorrow and once I land that/confirm it working I'll make the merge.

**Comment by rmusser01** [comment]
Ok, I'm going to merge it now. 
I've added in rolling summarization support via OpenAI through their sample.
`python summarize.py -api openai -rolling -detail <0.01-1.0> <URL/Txt file>`

I notice that you had support for exllama and vLLM, though my understanding is that it was limited to llama 2 due to the tokenization aspect.
I need to look further into how to approach enabling tokenization support for the largest range of models/figure something out for self-hosters besides just saying 'lol only use XYZ models for rolling summarization'... Though in reality I suppose that is what it comes down to anyways in terms of effectiveness.
So I'll look to target support for MS Phi-3 and Llama3 as the two primary ones, with additional focus after those two are supported.

**Pull request merged**
